"""Tests for CookieImportDialog — YouTube cookie import via file/paste/Google login.

Phase 40 Plan 03: UI-09 feature.

All tests use paths._root_override to redirect file writes to tmp_path.
QFileDialog and QProcess are mocked so tests run headless without real I/O.
"""
from __future__ import annotations

import os
import stat
from unittest.mock import MagicMock, patch, call

import pytest

from musicstreamer import paths


# ---------------------------------------------------------------------------
# Validation function tests (pure, no Qt required)
# ---------------------------------------------------------------------------

def test_paste_validation_valid():
    """A line with .youtube.com domain passes validation."""
    from musicstreamer.ui_qt.cookie_import_dialog import _validate_youtube_cookies
    text = ".youtube.com\tFALSE\t/\tFALSE\t0\tCOOKIE\tvalue"
    assert _validate_youtube_cookies(text) is True


def test_paste_validation_invalid():
    """Text with no .youtube.com domain fails validation."""
    from musicstreamer.ui_qt.cookie_import_dialog import _validate_youtube_cookies
    text = ".example.com\tFALSE\t/\tFALSE\t0\tCOOKIE\tvalue"
    assert _validate_youtube_cookies(text) is False


def test_paste_validation_empty():
    """Empty string fails validation."""
    from musicstreamer.ui_qt.cookie_import_dialog import _validate_youtube_cookies
    assert _validate_youtube_cookies("") is False


def test_paste_validation_comments_only():
    """Lines starting with # are skipped; no .youtube.com line → False."""
    from musicstreamer.ui_qt.cookie_import_dialog import _validate_youtube_cookies
    text = "# This is a Netscape cookie file\n# Generated by Chrome"
    assert _validate_youtube_cookies(text) is False


def test_paste_validation_mixed_with_youtube():
    """Mixed cookies file with one .youtube.com line → True."""
    from musicstreamer.ui_qt.cookie_import_dialog import _validate_youtube_cookies
    text = (
        "# Netscape HTTP Cookie File\n"
        ".google.com\tFALSE\t/\tFALSE\t0\tSID\tabc\n"
        ".youtube.com\tFALSE\t/\tFALSE\t0\tVISITOR_INFO1_LIVE\tdef\n"
    )
    assert _validate_youtube_cookies(text) is True


# ---------------------------------------------------------------------------
# Dialog structure tests (require Qt)
# ---------------------------------------------------------------------------

def test_dialog_has_three_tabs(qtbot):
    """QTabWidget contains tabs named 'File', 'Paste', 'Google Login'."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=lambda msg: None)
    qtbot.addWidget(dlg)

    # Find the QTabWidget
    from PySide6.QtWidgets import QTabWidget
    tabs = dlg.findChild(QTabWidget)
    assert tabs is not None

    tab_count = tabs.count()
    assert tab_count == 3

    tab_names = [tabs.tabText(i) for i in range(tab_count)]
    assert "File" in tab_names
    assert "Paste" in tab_names
    assert "Google Login" in tab_names


def test_paste_import_button_disabled_when_empty(qtbot):
    """Import button on Paste tab is disabled when textarea is empty."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=lambda msg: None)
    qtbot.addWidget(dlg)

    assert not dlg._paste_import_btn.isEnabled()


def test_paste_import_button_enabled_when_text_entered(qtbot):
    """Import button on Paste tab becomes enabled when text is entered."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=lambda msg: None)
    qtbot.addWidget(dlg)

    dlg._paste_edit.setPlainText("some text")
    assert dlg._paste_import_btn.isEnabled()


def test_invalid_paste_shows_error(qtbot):
    """Pasting invalid cookie text and clicking Import shows inline error label."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=lambda msg: None)
    qtbot.addWidget(dlg)

    dlg._paste_edit.setPlainText(".example.com\tFALSE\t/\tFALSE\t0\tCOOKIE\tvalue")
    dlg._paste_import_btn.click()

    # isHidden() checks the widget's own explicit flag (not parent propagation)
    assert not dlg._error_label.isHidden()
    assert "Invalid cookies" in dlg._error_label.text()


def test_error_label_hidden_initially(qtbot):
    """Error label is hidden when dialog first opens."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=lambda msg: None)
    qtbot.addWidget(dlg)

    assert dlg._error_label.isHidden()


# ---------------------------------------------------------------------------
# _write_cookies: file write + permissions
# ---------------------------------------------------------------------------

def test_write_cookies_creates_file_with_correct_permissions(tmp_path, monkeypatch, qtbot):
    """_write_cookies writes content to cookies_path() with 0o600 permissions."""
    monkeypatch.setattr(paths, "_root_override", str(tmp_path))

    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=lambda msg: None)
    qtbot.addWidget(dlg)

    cookie_text = ".youtube.com\tFALSE\t/\tFALSE\t0\tVISITOR\tval"
    dlg._write_cookies(cookie_text)

    cookie_file = tmp_path / "cookies.txt"
    assert cookie_file.exists()
    assert cookie_file.read_text() == cookie_text

    file_mode = stat.S_IMODE(os.stat(str(cookie_file)).st_mode)
    assert file_mode == 0o600


def test_paste_import_writes_cookies(tmp_path, monkeypatch, qtbot):
    """Valid paste text + Import click writes to cookies_path()."""
    monkeypatch.setattr(paths, "_root_override", str(tmp_path))

    toasts = []
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=toasts.append)
    qtbot.addWidget(dlg)

    cookie_text = ".youtube.com\tFALSE\t/\tFALSE\t0\tVISITOR\tval"
    dlg._paste_edit.setPlainText(cookie_text)
    dlg._paste_import_btn.click()

    cookie_file = tmp_path / "cookies.txt"
    assert cookie_file.exists()
    assert "YouTube cookies imported." in toasts


# ---------------------------------------------------------------------------
# File tab: _on_choose_file + _on_file_import
# ---------------------------------------------------------------------------

def test_file_import_writes_with_permissions(tmp_path, monkeypatch, qtbot):
    """Choosing a valid cookie file and clicking Import writes with 0o600 perms."""
    monkeypatch.setattr(paths, "_root_override", str(tmp_path))

    # Create a valid source cookie file
    source = tmp_path / "my_cookies.txt"
    cookie_text = ".youtube.com\tFALSE\t/\tFALSE\t0\tVISITOR\tval"
    source.write_text(cookie_text)

    toasts = []
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=toasts.append)
    qtbot.addWidget(dlg)

    # Simulate the user picking a file (bypass QFileDialog)
    dlg._selected_file_path = str(source)
    dlg._file_label.setText(source.name[:40])
    dlg._file_import_btn.setVisible(True)

    dlg._on_file_import()

    cookie_file = tmp_path / "cookies.txt"
    assert cookie_file.exists()
    assert cookie_file.read_text() == cookie_text
    file_mode = stat.S_IMODE(os.stat(str(cookie_file)).st_mode)
    assert file_mode == 0o600
    assert "YouTube cookies imported." in toasts


def test_file_import_shows_error_on_empty_file(tmp_path, monkeypatch, qtbot):
    """Choosing an empty file shows 'File is empty.' error."""
    monkeypatch.setattr(paths, "_root_override", str(tmp_path))

    source = tmp_path / "empty_cookies.txt"
    source.write_text("")

    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    dlg = CookieImportDialog(toast_callback=lambda msg: None)
    qtbot.addWidget(dlg)

    dlg._selected_file_path = str(source)
    dlg._file_label.setText(source.name[:40])
    dlg._file_import_btn.setVisible(True)

    dlg._on_file_import()

    assert not dlg._error_label.isHidden()
    assert "File is empty" in dlg._error_label.text()


# ---------------------------------------------------------------------------
# Google Login tab: QProcess launch
# ---------------------------------------------------------------------------

def test_google_login_launches_qprocess(qtbot, monkeypatch):
    """Clicking 'Open Google Login' starts QProcess with oauth_helper --mode google."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog

    mock_process = MagicMock()
    with patch("musicstreamer.ui_qt.cookie_import_dialog.QProcess", return_value=mock_process):
        dlg = CookieImportDialog(toast_callback=lambda msg: None)
        qtbot.addWidget(dlg)
        dlg._on_google_login()

    mock_process.start.assert_called_once()
    # Verify sys.executable used as program (not a shell call)
    start_args = mock_process.start.call_args
    import sys
    assert start_args[0][0] == sys.executable
    assert "--mode" in start_args[0][1]
    assert "google" in start_args[0][1]


# ---------------------------------------------------------------------------
# Phase 60 / GBS-01b: parameterization regression + new coverage
# ---------------------------------------------------------------------------

def test_dialog_default_construction_preserves_youtube_behavior(qtbot, tmp_path, monkeypatch):
    """Regression — passing only the legacy positional args still configures YouTube."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    from musicstreamer import paths
    captured_toasts = []
    dlg = CookieImportDialog(toast_callback=captured_toasts.append)
    qtbot.addWidget(dlg)
    assert dlg.windowTitle() == "YouTube Cookies"
    assert dlg._target_label == "YouTube"
    assert dlg._cookies_path is paths.cookies_path
    assert dlg._oauth_mode == "google"
    # 3 tabs: File / Paste / Google Login
    assert dlg._tabs.count() == 3


def test_dialog_gbs_construction_omits_oauth_tab(qtbot, tmp_path, monkeypatch):
    """Phase 60 D-04: GBS dialog has File + Paste tabs only when oauth_mode=None."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    from musicstreamer import paths, gbs_api
    captured_toasts = []
    dlg = CookieImportDialog(
        toast_callback=captured_toasts.append,
        target_label="GBS.FM",
        cookies_path=paths.gbs_cookies_path,
        validator=gbs_api._validate_gbs_cookies,
        oauth_mode=None,
    )
    qtbot.addWidget(dlg)
    assert dlg.windowTitle() == "GBS.FM Cookies"
    assert dlg._target_label == "GBS.FM"
    assert dlg._cookies_path is paths.gbs_cookies_path
    assert dlg._oauth_mode is None
    # 2 tabs only — no OAuth tab
    assert dlg._tabs.count() == 2


def test_gbs_paste_invalid_shows_target_specific_error(qtbot, monkeypatch):
    """Validator + error string parameterized for GBS.FM."""
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    from musicstreamer import paths, gbs_api
    captured_toasts = []
    dlg = CookieImportDialog(
        toast_callback=captured_toasts.append,
        target_label="GBS.FM",
        cookies_path=paths.gbs_cookies_path,
        validator=gbs_api._validate_gbs_cookies,
        oauth_mode=None,
    )
    qtbot.addWidget(dlg)
    # Paste plainly invalid content
    dlg._paste_edit.setPlainText("# garbage")
    dlg._on_paste_import()
    assert not dlg._error_label.isHidden()
    assert "GBS.FM" in dlg._error_label.text()


def test_gbs_paste_valid_writes_to_gbs_cookies_path(qtbot, tmp_path, monkeypatch):
    """Phase 60 D-04 + Phase 999.7 0o600: write goes to gbs_cookies_path; perms are 0o600."""
    import os
    from musicstreamer.ui_qt.cookie_import_dialog import CookieImportDialog
    from musicstreamer import paths, gbs_api
    monkeypatch.setattr(paths, "_root_override", str(tmp_path))
    os.makedirs(str(tmp_path), exist_ok=True)  # HIGH 3: explicit setup boilerplate
    captured_toasts = []
    dlg = CookieImportDialog(
        toast_callback=captured_toasts.append,
        target_label="GBS.FM",
        cookies_path=paths.gbs_cookies_path,
        validator=gbs_api._validate_gbs_cookies,
        oauth_mode=None,
    )
    qtbot.addWidget(dlg)
    valid_cookies = (
        "# Netscape HTTP Cookie File\n"
        ".gbs.fm\tTRUE\t/\tTRUE\t9999999999\tcsrftoken\tabc123\n"
        "gbs.fm\tFALSE\t/\tTRUE\t9999999999\tsessionid\txyz789\n"
    )
    dlg._paste_edit.setPlainText(valid_cookies)
    dlg._on_paste_import()
    target = paths.gbs_cookies_path()
    assert os.path.exists(target)
    # Content matches
    with open(target) as f:
        assert "sessionid" in f.read()
    # 0o600 perms (Phase 999.7 convention)
    mode = os.stat(target).st_mode & 0o777
    assert mode == 0o600
    # Toast text uses target_label
    assert any("GBS.FM cookies imported" in t for t in captured_toasts)
