"""Shared helpers for cookies.txt handling.

Provides:
  - is_cookie_file_corrupted(path) -> bool
      Pure predicate; returns True iff the file starts with the yt-dlp save
      header (see yt_dlp/cookies.py:1284).
  - temp_cookies_copy() -> Iterator[Optional[str]]
      @contextmanager that yields a per-call tempfile copy of paths.cookies_path(),
      or None when the canonical file is absent or shutil.copy2 raises OSError.
      Always unlinks the tempfile in finally (even on exception).

Phase 999.7 — restores the v1.5 FIX-02 protection that was lost when Plan
35-06 replaced the mpv subprocess with the yt_dlp library API. Call sites:
  - musicstreamer/player.py::_youtube_resolve_worker
  - musicstreamer/yt_import.py::scan_playlist

Reference: docs.python.org/3/library/contextlib.html#contextlib.contextmanager
"""
from __future__ import annotations

import contextlib
import os
import shutil
import tempfile
from typing import Iterator, Optional

from musicstreamer import paths


_YTDLP_MARKER = "generated by yt-dlp"


def is_cookie_file_corrupted(path: str) -> bool:
    """Return True if ``path`` was written by yt-dlp's save_cookies().

    Detects the yt-dlp save header by scanning the first 4 non-blank lines
    for the substring 'generated by yt-dlp'. Returns False on OSError
    (missing file, permission denied) — mirrors ``constants.clear_cookies``'s
    forgive-cleanup posture.
    """
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            head = fh.read(512)
    except OSError:
        return False
    for line in head.splitlines()[:4]:
        if _YTDLP_MARKER in line:
            return True
    return False


@contextlib.contextmanager
def temp_cookies_copy() -> Iterator[Optional[str]]:
    """Yield a path to a per-call temp copy of paths.cookies_path(), or None.

    Yields None when:
      - canonical cookies.txt does not exist
      - shutil.copy2 raises OSError (disk full / permissions)

    The temp file is unlinked in ``finally`` regardless of exception. Uses
    tempfile.mkstemp (not NamedTemporaryFile) for cross-platform safety —
    Windows cannot reopen a still-open NamedTemporaryFile (v2.0 port
    constraint).
    """
    canonical = paths.cookies_path()
    if not os.path.exists(canonical):
        yield None
        return

    fd, tmp_path = tempfile.mkstemp(prefix="ms-cookies-", suffix=".txt")
    os.close(fd)
    try:
        try:
            shutil.copy2(canonical, tmp_path)
        except OSError:
            yield None
            return
        yield tmp_path
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass  # best-effort cleanup
